homeassistant:
  name: Seowoo
  latitude: !secret latitude_loc
  longitude: !secret longitude_loc
  elevation: !secret elevation_loc
  unit_system: metric
  time_zone: Asia/Seoul
  customize: !include customize.yaml

# seowoo
http:
  api_password: !secret http_password
  # Set to 1 to enable development mode
  # development: 1

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Enables the frontend
frontend:

device_tracker:

logger:
  default: error
  logs:
    homeassistant.components.device_tracker: critical
    pyAqara.gateway: debug

switch:
  - platform: orvibo
    discovery: false
    switches:
      - host: 192.168.31.11
        mac : ac:cf:23:65:95:64
        name: "5th (F)"

      - host: 192.168.31.12
        mac : ac:cf:23:65:eb:14
        name: "5th (M)"

      - host: 192.168.31.13
        mac : ac:cf:23:65:97:18
        name: "6th (M)"

      - host: 192.168.31.14
        mac : ac:cf:23:65:e4:34
        name: "6th (F)"

group:
  5th floor:
    - switch.5th_m
    - switch.5th_f
  6th floor:
    - binary_sensor.magnet_158d0000f4f404
    - sensor.temperature_158d0000f19c74
    - sensor.humidity_158d0000f19c74
    - switch.6th_m
    - switch.6th_f
  raspberry pi:
    - sensor.cpu_use
    - sensor.ram_free
    - script.reboot_pi

aqara:
  gateway_password: !secret aqara_password

sensor owm:
  platform: openweathermap
  api_key: !secret owm_key
  forecast: 0
  monitored_conditions:
    - weather
    - temperature
    - humidity

notify:
  platform: telegram
  api_key: !secret telegram_key
  chat_id: !secret telegram_chat_id

# raspberry
sensor pi:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_free

script:
  reboot_pi:
    alias: Reboot PI
    sequence:
      - alias: Reboot PI
        service: shell_command.reboot_pi

shell_command:
  reboot_pi: sudo reboot

# Automation
automation: !include_dir_list automation
