homeassistant:
  name: Seowoo
  latitude: !secret latitude_loc
  longitude: !secret longitude_loc
  elevation: !secret elevation_loc
  unit_system: metric
  time_zone: Asia/Seoul

# seowoo
http:
  api_password: !secret http_password
  # Set to 1 to enable development mode
  # development: 1

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Enables the frontend
frontend:

device_tracker:

logger:
  default: error
  logs:
    homeassistant.components.device_tracker: critical

switch:
  - platform: orvibo
    discovery: false
    switches:
      - host: 192.168.31.11
        mac : ac:cf:23:65:95:64
        name: "5th (F)"

      - host: 192.168.31.12
        mac : ac:cf:23:65:eb:14
        name: "5th (M)"

      - host: 192.168.31.13
        mac : ac:cf:23:65:97:18
        name: "6th (M)"

      - host: 192.168.31.14
        mac : ac:cf:23:65:e4:34
        name: "6th (F)"

group:
  5th_floor:
    - switch.5th_m
    - switch.5th_f
  6th_floor:
    - binary_sensor.6th_window
    - sensor.6th_temperature
    - sensor.6th_humidity
    - switch.6th_m
    - switch.6th_f
  raspberry pi:
    - sensor.cpu_use
    - sensor.ram_free
    - script.reboot_pi

mqtt:
  broker: localhost
  port: 1883
  client_id: hass
  keepalive: 60
  protocol: 3.1

binary_sensor:
  - platform: mqtt
    state_topic: 'xiaomi/magnet/158d0000f4f404/status'
    name: "6th Window"
    sensor_class: opening
    payload_on: "open"
    payload_off: "close"

sensor pi:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_free

sensor 6th:
  - platform: mqtt
    state_topic: 'xiaomi/sensor_ht/158d0000f19c74/temperature'
    name: '6th Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ float(value) / 100 }}'
  - platform: mqtt
    state_topic: 'xiaomi/sensor_ht/158d0000f19c74/humidity'
    name: '6th Humidity'
    unit_of_measurement: '%'
    value_template: '{{ float(value) / 100 }}'

sensor owm:
  platform: openweathermap
  api_key: !secret owm_key
  forecast: 0
  monitored_conditions:
    - weather
    - temperature
    - humidity

notify:
  platform: telegram
  api_key: !secret telegram_key
  chat_id: !secret telegram_chat_id

script:
  reboot_pi:
    alias: Reboot PI
    sequence:
      - alias: Reboot PI
        service: shell_command.reboot_pi

shell_command:
  reboot_pi: sudo reboot

# Automation
automation: !include_dir_list automation
