alias: 6m heater at close
trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_158d0000f19c74
    below: 1
  - platform: numeric_state
    entity_id: sensor.temperature_158d0000f19c74
    above: 4
condition:
  condition: time
  after: '00:00:00'
  before: '09:00:00'
action:
  - service: notify.notify
    data_template:
      title: 'ALERT'
      message: >
        6m temperature is {{ states('sensor.temperature_158d00010b3c99') }}
  - service_template: >
      {% if states('sensor.temperature_158d0000f19c74') | float < 1 %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    entity_id:
      - switch.6th_m
