alias: 6th floor heater at work
trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_158d0000f19c74
    below: 13
  - platform: numeric_state
    entity_id: sensor.temperature_158d0000f19c74
    above: 16
condition:
  condition: time
  after: '09:00:00'
  before: '23:50:00'
action:
  - service: notify.notify
    data_template:
      title: 'ALERT'
      message: >
        6th floor is {{ states('sensor.temperature_158d0000f19c74') }}
  - service_template: >
      {% if states('sensor.temperature_158d0000f19c74') | float < 13 %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    entity_id:
      - switch.6th_m
      - switch.6th_f
